[package]
name = "hello_bin"
version = "0.1.0"
authors = ["xl000 <l_xb@foxmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
